export const ROLE_DATA_MAP: { [key: string]: any[] } = {
  MVS_OFFICER: [
    { 'Application ID': '1000000001', Service: 'New Registration', 'Service Type': 'By Birth', 'Created Date': '2024-11-01' },
    { 'Application ID': '1000000002', Service: 'Renewal', 'Service Type': 'Type A', 'Created Date': '2024-11-02' },
    { 'Application ID': '1000000003', Service: 'Update/COP', 'Service Type': 'Type B', 'Created Date': '2024-11-03' },
    { 'Application ID': '1000000004', Service: 'Lost', 'Service Type': 'By Birth', 'Created Date': '2024-11-04' },
    { 'Application ID': '1000000005', Service: 'New Registration', 'Service Type': 'Type C', 'Created Date': '2024-11-05' },
    { 'Application ID': '1000000006', Service: 'Renewal', 'Service Type': 'By Birth', 'Created Date': '2024-11-06' },
    { 'Application ID': '1000000007', Service: 'Update/COP', 'Service Type': 'Type D', 'Created Date': '2024-11-07' },
    { 'Application ID': '1000000008', Service: 'Lost', 'Service Type': 'Type B', 'Created Date': '2024-11-08' },
    { 'Application ID': '1000000009', Service: 'New Registration', 'Service Type': 'By Birth', 'Created Date': '2024-11-09' },
    { 'Application ID': '1000000010', Service: 'Renewal', 'Service Type': 'Type A', 'Created Date': '2024-11-10' },
    { 'Application ID': '1000000011', Service: 'Update/COP', 'Service Type': 'Type C', 'Created Date': '2024-11-11' },
    { 'Application ID': '1000000012', Service: 'Lost', 'Service Type': 'By Birth', 'Created Date': '2024-11-12' },
    { 'Application ID': '1000000013', Service: 'New Registration', 'Service Type': 'Type D', 'Created Date': '2024-11-13' },
    { 'Application ID': '1000000014', Service: 'Renewal', 'Service Type': 'By Birth', 'Created Date': '2024-11-14' },
    { 'Application ID': '1000000015', Service: 'Update/COP', 'Service Type': 'Type B', 'Created Date': '2024-11-15' },
  ],
  MVS_SUPERVISOR: [
    {
      'Application ID': '2000000001',
      Service: 'New Registration',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-01',
      'Escalation Category': 'Category A',
      'Escalation Comment': 'Reason A',
      'Escalated Date': '2024-11-02',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000002',
      Service: 'Renewal',
      'Service Type': 'Type A',
      'Created Date': '2024-11-02',
      'Escalation Category': 'Category B',
      'Escalation Comment': 'Reason B',
      'Escalated Date': '2024-11-03',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000003',
      Service: 'Update/COP',
      'Service Type': 'Type B',
      'Created Date': '2024-11-03',
      'Escalation Category': 'Category C',
      'Escalation Comment': 'Reason C',
      'Escalated Date': '2024-11-04',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000004',
      Service: 'Lost',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-04',
      'Escalation Category': 'Category A',
      'Escalation Comment': 'Reason D',
      'Escalated Date': '2024-11-05',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000005',
      Service: 'New Registration',
      'Service Type': 'Type C',
      'Created Date': '2024-11-05',
      'Escalation Category': 'Category D',
      'Escalation Comment': 'Reason E',
      'Escalated Date': '2024-11-06',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000006',
      Service: 'Renewal',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-06',
      'Escalation Category': 'Category E',
      'Escalation Comment': 'Reason F',
      'Escalated Date': '2024-11-07',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000007',
      Service: 'Update/COP',
      'Service Type': 'Type D',
      'Created Date': '2024-11-07',
      'Escalation Category': 'Category F',
      'Escalation Comment': 'Reason G',
      'Escalated Date': '2024-11-08',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000008',
      Service: 'Lost',
      'Service Type': 'Type B',
      'Created Date': '2024-11-08',
      'Escalation Category': 'Category G',
      'Escalation Comment': 'Reason H',
      'Escalated Date': '2024-11-09',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000009',
      Service: 'New Registration',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-09',
      'Escalation Category': 'Category H',
      'Escalation Comment': 'Reason I',
      'Escalated Date': '2024-11-10',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000010',
      Service: 'Renewal',
      'Service Type': 'Type A',
      'Created Date': '2024-11-10',
      'Escalation Category': 'Category I',
      'Escalation Comment': 'Reason J',
      'Escalated Date': '2024-11-11',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000011',
      Service: 'Update/COP',
      'Service Type': 'Type C',
      'Created Date': '2024-11-11',
      'Escalation Category': 'Category J',
      'Escalation Comment': 'Reason K',
      'Escalated Date': '2024-11-12',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000012',
      Service: 'Lost',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-12',
      'Escalation Category': 'Category K',
      'Escalation Comment': 'Reason L',
      'Escalated Date': '2024-11-13',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000013',
      Service: 'New Registration',
      'Service Type': 'Type D',
      'Created Date': '2024-11-13',
      'Escalation Category': 'Category L',
      'Escalation Comment': 'Reason M',
      'Escalated Date': '2024-11-14',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '2000000014',
      Service: 'Renewal',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-14',
      'Escalation Category': 'Category M',
      'Escalation Comment': 'Reason N',
      'Escalated Date': '2024-11-15',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '2000000015',
      Service: 'Update/COP',
      'Service Type': 'Type B',
      'Created Date': '2024-11-15',
      'Escalation Category': 'Category N',
      'Escalation Comment': 'Reason O',
      'Escalated Date': '2024-11-16',
      'Application Status': 'Pending',
    },
  ],
  MVS_DISTRICT_OFFICER: [
    {
      'Application ID': '3000000001',
      Service: 'New Registration',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-01',
      'Escalation Category from MVS Officer': 'Category A',
      'Escalation Comment From MVS Officer': 'Reason A',
      'MVS Officer Escalated Date': '2024-11-02',
      'Escalation Category From MVS Supervisor': 'Supervisor Category A',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason A',
      'MVS Supervisor Escalated Date': '2024-11-03',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000002',
      Service: 'Renewal',
      'Service Type': 'Type A',
      'Created Date': '2024-11-02',
      'Escalation Category from MVS Officer': 'Category B',
      'Escalation Comment From MVS Officer': 'Reason B',
      'MVS Officer Escalated Date': '2024-11-03',
      'Escalation Category From MVS Supervisor': 'Supervisor Category B',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason B',
      'MVS Supervisor Escalated Date': '2024-11-04',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '3000000003',
      Service: 'Update/COP',
      'Service Type': 'Type B',
      'Created Date': '2024-11-03',
      'Escalation Category from MVS Officer': 'Category C',
      'Escalation Comment From MVS Officer': 'Reason C',
      'MVS Officer Escalated Date': '2024-11-04',
      'Escalation Category From MVS Supervisor': 'Supervisor Category C',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason C',
      'MVS Supervisor Escalated Date': '2024-11-05',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000004',
      Service: 'Lost',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-04',
      'Escalation Category from MVS Officer': 'Category D',
      'Escalation Comment From MVS Officer': 'Reason D',
      'MVS Officer Escalated Date': '2024-11-05',
      'Escalation Category From MVS Supervisor': 'Supervisor Category D',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason D',
      'MVS Supervisor Escalated Date': '2024-11-06',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '3000000005',
      Service: 'New Registration',
      'Service Type': 'Type C',
      'Created Date': '2024-11-05',
      'Escalation Category from MVS Officer': 'Category E',
      'Escalation Comment From MVS Officer': 'Reason E',
      'MVS Officer Escalated Date': '2024-11-06',
      'Escalation Category From MVS Supervisor': 'Supervisor Category E',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason E',
      'MVS Supervisor Escalated Date': '2024-11-07',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000006',
      Service: 'Renewal',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-06',
      'Escalation Category from MVS Officer': 'Category F',
      'Escalation Comment From MVS Officer': 'Reason F',
      'MVS Officer Escalated Date': '2024-11-07',
      'Escalation Category From MVS Supervisor': 'Supervisor Category F',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason F',
      'MVS Supervisor Escalated Date': '2024-11-08',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '3000000007',
      Service: 'Update/COP',
      'Service Type': 'Type D',
      'Created Date': '2024-11-07',
      'Escalation Category from MVS Officer': 'Category G',
      'Escalation Comment From MVS Officer': 'Reason G',
      'MVS Officer Escalated Date': '2024-11-08',
      'Escalation Category From MVS Supervisor': 'Supervisor Category G',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason G',
      'MVS Supervisor Escalated Date': '2024-11-09',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000008',
      Service: 'Lost',
      'Service Type': 'Type B',
      'Created Date': '2024-11-08',
      'Escalation Category from MVS Officer': 'Category H',
      'Escalation Comment From MVS Officer': 'Reason H',
      'MVS Officer Escalated Date': '2024-11-09',
      'Escalation Category From MVS Supervisor': 'Supervisor Category H',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason H',
      'MVS Supervisor Escalated Date': '2024-11-10',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '3000000009',
      Service: 'New Registration',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-09',
      'Escalation Category from MVS Officer': 'Category I',
      'Escalation Comment From MVS Officer': 'Reason I',
      'MVS Officer Escalated Date': '2024-11-10',
      'Escalation Category From MVS Supervisor': 'Supervisor Category I',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason I',
      'MVS Supervisor Escalated Date': '2024-11-11',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000010',
      Service: 'Renewal',
      'Service Type': 'Type A',
      'Created Date': '2024-11-10',
      'Escalation Category from MVS Officer': 'Category J',
      'Escalation Comment From MVS Officer': 'Reason J',
      'MVS Officer Escalated Date': '2024-11-11',
      'Escalation Category From MVS Supervisor': 'Supervisor Category J',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason J',
      'MVS Supervisor Escalated Date': '2024-11-12',
      'Application Status': 'Scheduled For Interview',
    },
    {
      'Application ID': '3000000011',
      Service: 'Update/COP',
      'Service Type': 'Type C',
      'Created Date': '2024-11-11',
      'Escalation Category from MVS Officer': 'Category K',
      'Escalation Comment From MVS Officer': 'Reason K',
      'MVS Officer Escalated Date': '2024-11-12',
      'Escalation Category From MVS Supervisor': 'Supervisor Category K',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason K',
      'MVS Supervisor Escalated Date': '2024-11-13',
      'Application Status': 'Pending',
    },
    {
      'Application ID': '3000000012',
      Service: 'Lost',
      'Service Type': 'By Birth',
      'Created Date': '2024-11-12',
      'Escalation Category from MVS Officer': 'Category L',
      'Escalation Comment From MVS Officer': 'Reason L',
      'MVS Officer Escalated Date': '2024-11-13',
      'Escalation Category From MVS Supervisor': 'Supervisor Category L',
      'Escalation Comment From MVS Supervisor': 'Supervisor Reason L',
      'MVS Supervisor Escalated Date': '2024-11-14',
      'Application Status': 'Scheduled For Interview',
    },
  ],
  MVS_LEGAL_OFFICER: [
    { 'Application ID': '1000000001', Service: 'New Registration', 'Service Type': 'By Birth', 'Created Date': '2024-11-01' },
    { 'Application ID': '1000000002', Service: 'Renewal', 'Service Type': 'Type A', 'Created Date': '2024-11-02' },
    { 'Application ID': '1000000003', Service: 'Update/COP', 'Service Type': 'Type B', 'Created Date': '2024-11-03' },
    { 'Application ID': '1000000004', Service: 'Lost', 'Service Type': 'By Birth', 'Created Date': '2024-11-04' },
    { 'Application ID': '1000000005', Service: 'New Registration', 'Service Type': 'Type C', 'Created Date': '2024-11-05' },
    { 'Application ID': '1000000006', Service: 'Renewal', 'Service Type': 'By Birth', 'Created Date': '2024-11-06' },
    { 'Application ID': '1000000007', Service: 'Update/COP', 'Service Type': 'Type D', 'Created Date': '2024-11-07' },
    { 'Application ID': '1000000008', Service: 'Lost', 'Service Type': 'Type B', 'Created Date': '2024-11-08' },
    { 'Application ID': '1000000009', Service: 'New Registration', 'Service Type': 'By Birth', 'Created Date': '2024-11-09' },
    { 'Application ID': '1000000010', Service: 'Renewal', 'Service Type': 'Type A', 'Created Date': '2024-11-10' },
    { 'Application ID': '1000000011', Service: 'Update/COP', 'Service Type': 'Type C', 'Created Date': '2024-11-11' },
    { 'Application ID': '1000000012', Service: 'Lost', 'Service Type': 'By Birth', 'Created Date': '2024-11-12' },
    { 'Application ID': '1000000013', Service: 'New Registration', 'Service Type': 'Type D', 'Created Date': '2024-11-13' },
    { 'Application ID': '1000000014', Service: 'Renewal', 'Service Type': 'By Birth', 'Created Date': '2024-11-14' },
    { 'Application ID': '1000000015', Service: 'Update/COP', 'Service Type': 'Type B', 'Created Date': '2024-11-15' },
  ],
};
